version: "3.8"

services:
    db:
        image: postgres:16.3-alpine
        restart: always
        volumes:
            - pgdata_authzed:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_NAME}
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT} -d ${POSTGRES_DB_NAME}
            interval: 1s
            timeout: 3s
            retries: 5

    authzed_spicedb:
        build:
            context: ./docker/authzed/
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        ports:
            - "${SPICEDB_GRPC_ADDR}:${SPICEDB_GRPC_ADDR}"
            - "${SPICEDB_HTTP_PORT}:${SPICEDB_HTTP_PORT}"
            - "${SPICEDB_DASHBORD_PORT}:${SPICEDB_DASHBORD_PORT}"
        command: >
            serve --dashboard-addr :${SPICEDB_DASHBORD_PORT} --metrics-enabled=false --telemetry-endpoint= --skip-release-check=true
            --http-enabled --http-addr :${SPICEDB_HTTP_PORT} --grpc-addr :${SPICEDB_GRPC_ADDR}
            --datastore-engine postgres --datastore-conn-max-open 500


volumes:
    pgdata_authzed:
